# 1. Change the prefix from C-b to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Enable mouse mode (scrolling, resizing panes, clicking tabs)
set -g mouse on

# Easy config reload
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# enter windows and panes on the same as current dir
bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Start window and pane numbering at 1 (instead of 0)
# This matches your keyboard layout (1 is on the left, 0 is on the far right)
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows automatically when one is closed
set -g renumber-windows on

# Improve colors (makes things look like your iTerm2 theme)
set -g default-terminal "screen-256color"

set -g status-keys vi

bind J resize-pane -D 16
bind K resize-pane -U 15
# bind shift-enter for tmux to C-j, for claude code
bind-key -T root S-Enter send-keys C-j

# focus events
set -g focus-events on

# pi said to try it for enter keys
set -g extended-keys on
set -g extended-keys-format csi-u

# https://hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/
setw -g clock-mode-colour yellow
setw -g mode-style 'fg=black bg=magenta'
set -g pane-border-style 'fg=magenta'
set -g pane-active-border-style 'fg=cyan'

# set the pane border status
set -g pane-border-status top
set-option -g detach-on-destroy off
