# 1. Change the prefix from C-b to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# 2. Enable mouse mode (scrolling, resizing panes, clicking tabs)
set -g mouse on

# 3. Easy config reload
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# 4. Use | and - to split windows (much more intuitive than % and ")
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Start window and pane numbering at 1 (instead of 0)
# This matches your keyboard layout (1 is on the left, 0 is on the far right)
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows automatically when one is closed
set -g renumber-windows on

# Improve colors (makes things look like your iTerm2 theme)
set -g default-terminal "screen-256color"

set -g status-keys vi
setw -g mode-mouse on

bind J resize-pane -D 15
bind K resize-pane -U 15
